services:
  - type: web
    name: ofsg-platform
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python ofsg_platform/manage.py collectstatic --noinput"
    startCommand: "cd ofsg_platform && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    # Run migrations on each deploy to ensure DB schema is up-to-date
    releaseCommand: "cd ofsg_platform && python manage.py migrate --noinput && python manage.py seed_demo_users"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECURE_SSL_REDIRECT
        value: "True"
