# Generated by Django 5.1.4 on 2026-07-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_guardian_1_member_guardian_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='members/id_documents/'),
        ),
        migrations.AddField(
            model_name='member',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/passport_photos/'),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='members/profile_pictures/'),
        ),
    ]
