# Generated by Django 4.2.30 on 2026-07-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_id_document_member_passport_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='members/passport_photos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='members/profile_pictures/'),
        ),
    ]
