# Generated by Django 5.1.4 on 2026-07-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_passport_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='member',
            name='passport_photo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_picture',
        ),
    ]
